### ISSUE TITLE
Flag's placement

### ISSUE THREAD

**Issue by SkyWors** [Khajiitos/ServerCountryFlags#1]
Hey! Very great mod! :smile: 
The actual flag's placement can hide some motd parts.
![image](https://user-images.githubusercontent.com/70440695/228506426-10d475fa-9518-4fa8-9219-d5fed31ffd79.png)
Maybe move it before the server title can be a good idea?
![image](https://user-images.githubusercontent.com/70440695/228506591-05f8e017-368c-4e2d-b2d1-e8682d678388.png)
This can be an option btw :thinking:

**Comment by Khajiitos** [comment]
Hi, thanks for your feedback! I'm planning to add an option that can move the flag before the server icon, and after the scrollbar. Making the flag appear before the server title will require the flag to be much smaller, I'm not sure how that would look like, but I will definitely experiment with that. Stay tuned for the next update :)

**Comment by SkyWors** [comment]
That will be great! Are you planning to add an in-game config with modmenu to manipulate those future implementatations?

**Comment by Khajiitos** [comment]
Probably not, since I have no idea where the button leading to the config would be, and some mods significantly change the menus (for example Sodium and Video Settings), or add their own stuff, which might make our button wrongly placed. 
But hey, at least the servercountryflags.properties file makes the game update the config live instead of having to reload the game :smile:

**Comment by SkyWors** [comment]
Yeah, it's difficult to find a good placement with all the others mods. Btw, in modmenu, there is this buttons who permit the access to the following mod's settings.
![image](https://user-images.githubusercontent.com/70440695/228576151-7e8efec4-78b3-4fee-85b5-e33ae345f58a.png)
![image](https://user-images.githubusercontent.com/70440695/228576278-00f065c2-3899-4a70-9cf9-b1d1e707a2f9.png)
I forget about the .properties file, thanks for remind me about it :smile:

**Comment by Khajiitos** [comment]
The flag can now be moved behind the server name in the latest version, as you suggested. You can do that by setting **flagPosition** to **_behindName_** in the properties file :)
