### ISSUE TITLE
[Feature]: Additional Hover Tooltip Flag Position

### ISSUE THREAD

**Issue by BioTechproject27** [Khajiitos/ServerCountryFlags#11]
Currently (1.9.3) there are 4 available flag positions:
`Behind Name`, `Left`, `Right`, `Default`
I'd suggest a fifth member: As a hovering tooltip.
For if ppl don't want to see the flags all the time. :D
 
 
 
 
Btw, on a completely seperate note, in ModMenu the order of options on the hovering tooltip of `Flag Position:` is shown as
`default, left, right, behindName`
but it cycles through
`Behind Name, Left, Right, Default`
And it starts with Behind Name, making the `Default` not technically the `Default`
Just a little cleanup would make it prettier <3

**Comment by Khajiitos** [comment]
Thanks for the suggestion! I like this idea a lot and I will look into adding it some time in the future!

**Comment by Khajiitos** [comment]
I added two new settings: Tooltip (Server Name), which shows the location when hovering over the server name and Tooltip (Ping), which adds the location to the ping tooltip, in the latest 1.10.0 update. I don't display flags inside the tooltip as I couldn't get it to work reliably, but this is a plan for sometime in the future :)
