### ISSUE TITLE
Compatibility for Raknetify 

### ISSUE THREAD

**Issue by sternschnaube** [Khajiitos/ServerCountryFlags#13]
https://modrinth.com/plugin/raknetify

Adding the prefix "raknet;" or "raknetl;" to the server address ends with an unknown location.

**Comment by Khajiitos** [comment]
Doesn't hurt to add compatibility, I'll release an update sometime soon :)

**Comment by sternschnaube** [comment]
Sounds great - thank you!

**Comment by Khajiitos** [comment]
Done and uploaded!
