### ISSUE TITLE
Broken font with this mod

### ISSUE THREAD

**Issue by variety754** [Khajiitos/ServerCountryFlags#2]
I have no font, everything in squares when using this mod. I think the problem is in my modpack dashloader is installed, but I'm not sure

**Comment by Khajiitos** [comment]
Hi, it turns out the issue might not actually be another mod, but lack of compability with 1.19.2, potentially 1.19.3, due to my lack of testing on these versions. I'm working on getting a fix for these versions.

**Comment by variety754** [comment]
Yes, it happened on 1.19.3 Fabric for me. Thank you for fast response, good luck with working on mod!

**Comment by Khajiitos** [comment]
The latest version should now work with 1.19.2 and 1.19.3. Thanks a lot for submitting this issue, I was always thinking that the mod would work fine on those versions. If you notice any problems while using your other mods, I would love if you could create another issue.
