### ISSUE TITLE
If I will change network when I'm already in Minecraft SCF will not see my new location

### ISSUE THREAD

**Issue by variety754** [Khajiitos/ServerCountryFlags#4]
I was using a British VPN first. When set to off without restarting Minecraft SCF still shows my location as Great Britain. Refresh button don't change anything.

**Comment by Khajiitos** [comment]
Hi, thanks for reporting this issue! I will look into it soon.

**Comment by Khajiitos** [comment]
Refreshing the server list should also refresh the local location if it had changed in the latest version. Thanks for reporting this!
