### ISSUE TITLE
[Suggestion] Make sorting by a country

### ISSUE THREAD

**Issue by variety754** [Khajiitos/ServerCountryFlags#5]
Functionality of your mod already is fine. I think it's a good time to fill it with new features! First that came to my mind:
Make a sorting feature, that lets sort servers by country with options:
1. From farthest to closest
2. From closest to farthest
3. Disable a specific country from showing up in list of servers
4. Sort by ping from lowest to highest
5. Sort by ping from highest to lowest

Another suggestion is to add compatibility with Server Browser to make sorting even more useful. If it's possible of course.

**Comment by Khajiitos** [comment]
Since it takes a while to get this information about servers, and that mostly only servers visible on the screen get pinged, I don't think real-time sorting would be a great idea, especially for a mod that just adds flags. Just a question, do flags show up in the Server Browser mod too?

**Comment by variety754** [comment]
No, they are not showing up.
Sorry to bother you, thought it was a good idea that came to my mind.

**Comment by Khajiitos** [comment]
No worries! Although making the mod work with the Server Browser might be something to think about.

**Comment by Khajiitos** [comment]
I still don't think this will be implemented for the reasons above.
