### ISSUE TITLE
Unreadable Characters

### ISSUE THREAD

**Issue by QueenUlyana** [Khajiitos/ServerCountryFlags#6]
@Khajiitos Unreadable Characters.
Add the ability to move the icon to another location, it overlaps the icons of other mods.

![2023-05-30_20 12 51](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/9d937b06-42f7-4bae-b457-8c1d1aeb2a29)
![2023-05-30_20 12 52](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/fdc3af5f-93b6-47fe-b72f-e5504fa99a08)
![2023-05-30_20 13 41](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/d2ffd40f-15b6-4272-adcf-85c78ba98ff3)
![2023-05-30_20 14 39](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/cb2da973-529a-4182-8c31-b5e790e490c1)
![2023-05-30_20 14 40](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/c8814019-11d9-4856-bfda-5c2437b510e9)

**Comment by Khajiitos** [comment]
By saying icon, do you mean the world map button?
What version of Minecraft did the issue occur in? What version of Server Country Flags did you use? What mods did you have installed? This will help figure out the issue.

**Comment by QueenUlyana** [comment]
> By saying icon, do you mean the world map button? What version of Minecraft did the issue occur in? What version of Server Country Flags did you use? What mods did you have installed? This will help figure out the issue.

Minecraft Version: 1.19.4 
servercountryflags-1.6.2-1.17-1.19.jar
I have a lot of mods installed, but in the example in the picture it is "In-Game Account Switcher". My native language is "Russian (Russia)", I just ask you to make sure that my language is displayed correctly and ability to modify the location of the map icon.

**Comment by Khajiitos** [comment]
Hi, I tried to verify this myself, but the text gets displayed as expected - can you verify if that happens without any other mods too?
![image](https://github.com/Khajiitos/ServerCountryFlags/assets/58109276/abc7a98f-da4a-4e0f-baea-26aef45c4c25)
The option to move the map button to the left side instead of the right side will be added in the next update.

**Comment by QueenUlyana** [comment]
> Hi, I tried to verify this myself, but the text gets displayed as expected - can you verify if that happens without any other mods too? ![image](https://user-images.githubusercontent.com/58109276/242945466-abc7a98f-da4a-4e0f-baea-26aef45c4c25.png) The option to move the map button to the left side instead of the right side will be added in the next update.

![2023-06-05_084216](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/fa472ae7-0385-4c7b-b2eb-08ca8ef05698)
![2023-06-05_08 41 49](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/11e2d177-b054-49ad-baa5-46b72cb5c2e9)
![2023-06-05_08 41 50](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/2ce4b78a-4028-4534-92e9-5c9ee9ccedc2)
![2023-06-05_08 41 56](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/f2621fbe-aa3d-4462-b0dc-6b0ccfd7588c)

**Comment by Khajiitos** [comment]
It's interesting that the text under the location gets displayed properly, and that the comma between the city and the country gets displayed too. The issue must be either that somehow we didn't get the response in a correct format somehow or that ipapi sends weird data for people from Russia (yeah... that might be a possibility). Can you open http://ip-api.com/json/hypixel.net?lang=ru in the browser and see if the response is correct?

**Comment by QueenUlyana** [comment]
> 

{"status":"success","country":"США","countryCode":"US","region":"NY","regionName":"Нью-Йорк","city":"Нью-Йорк","zip":"10123","lat":40.7128,"lon":-74.006,"timezone":"America/New_York","isp":"Cloudflare, Inc.","org":"Cloudflare, Inc.","as":"AS13335 Cloudflare, Inc.","query":"104.16.194.11"}

Yes, the Russian language is displayed correctly.

**Comment by QueenUlyana** [comment]
I don't know if it matters, but I use https://github.com/UltimMC/Launcher

**Comment by Khajiitos** [comment]
I uploaded a new version of the mod on CurseForge - it's a beta though so you might have to enable seeing alpha versions. It added an option to move the map button to the left side, and I changed something that could potentially fix this issue (not guaranteed)

**Comment by QueenUlyana** [comment]
> I uploaded a new version of the mod on CurseForge - it's a beta though so you might have to enable seeing alpha versions. It added an option to move the map button to the left side, and I changed something that could potentially fix this issue (not guaranteed)

Wow, it works. Only I forgot which library is needed to change the position of the map icon?

![2023-06-06_12 46 44](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/83881ac0-600d-4a20-89f4-75445bff84a3)
![2023-06-06_12 46 46](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/702cfc15-4d7d-40a9-8e90-f14b78041c08)

**Comment by QueenUlyana** [comment]
> The mod's config file is located in the config/servercountryflags/servercountryflags.properties file, the option to move the button to the left is mapButtonRight if I remember correctly, you will have to set its value to false.

Thanks, it worked.
![2023-06-06_13 09 44](https://github.com/Khajiitos/ServerCountryFlags/assets/83131824/63db8c3c-b232-4cc8-9bb1-635926122e39)
