### ISSUE TITLE
[Suggestion] Add the mod on modrinth

### ISSUE THREAD

**Issue by Finoway** [Khajiitos/ServerCountryFlags#7]
Hello,

I would like to be able to find the Server Country Flags on modrinth. Is that possible?

**Comment by Khajiitos** [comment]
Hi! For now you can't find the mod on Modrinth, although I've been thinking of including it there. Moreover, I'd like to implement a solution that will automatically upload the mod to those websites once a new version is released, instead of doing it manually.

**Comment by Finoway** [comment]
Hello, I just spoke with a friend he suggested this repo https://github.com/Kir-Antipov/mc-publish

**Comment by Khajiitos** [comment]
Once the mod passes verification, it will be available on Modrinth at: https://modrinth.com/mod/server-country-flags
You will only find the 1.20.x version of the mod there for now, I will upload the mod for older Minecraft versions soon.
